version: '3.9'

services:

  light_switcher:

    image: light_switcher
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      ["8000:5000"]

    command: ["uwsgi", "--http", "0.0.0.0:8000", "--module", "main:app"]
