FROM python:3.11.2-bullseye

WORKDIR /app

COPY requirements.txt requirements.txt

RUN python -m venv ./

RUN /bin/bash -c "source venv/bin/activate"

RUN pip install -r requirements.txt

CMD [ "python3", "main.py" ]