FROM python:3.11.2-bullseye

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN pip install uwsgi

COPY . .

CMD ["uwsgi", "--http", "0.0.0.0:5000", "--module", "main:app"]